name: Atualizar README com últimos repositórios

on:
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      GITHUB_USERNAME: LGstvexe
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - name: Checar código
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # desabilita o token automático do checkout para evitar conflito

    - name: Buscar últimos repositórios e atualizar README
      run: |
        sudo apt-get install jq

        repos=$(curl -s "https://api.github.com/users/$GITHUB_USERNAME/repos?sort=created&direction=desc&per_page=2")

        cards=""
        for row in $(echo "${repos}" | jq -r '.[] | @base64'); do
          _jq() {
            echo "${row}" | base64 --decode | jq -r "${1}"
          }
          name=$(_jq '.name')
          url=$(_jq '.html_url')
          cards+="[![Repo Card](https://github-readme-stats.vercel.app/api/pin/?username=$GITHUB_USERNAME&repo=$name&style=for-the-badge)]($url)\n"
        done

        awk -v cards="$cards" '
          /<!--START_REPOS-->/ {print; print cards; getline; getline; next}
          {print}
        ' README.md > README.tmp

        mv README.tmp README.md

        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git diff --cached --quiet || git commit -m "Atualiza cards dos últimos repositórios"
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${GITHUB_USERNAME}/LGstvexe.git
        git push origin main
